# Generated by Django 5.1.3 on 2024-12-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='Profesores',
            new_name='Moderator',
        ),
        migrations.RenameModel(
            old_name='Entregables',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='Vtuber',
        ),
        migrations.DeleteModel(
            name='Alumnos',
        ),
        migrations.RenameField(
            model_name='vtuber',
            old_name='comision',
            new_name='company',
        ),
    ]
