# Generated by Django 5.1.3 on 2024-12-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0003_post_foto_vtuber_descripcion_alter_vtuber_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='profesion',
        ),
        migrations.AddField(
            model_name='vtuber',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
