# Generated by Django 5.1.3 on 2024-12-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0004_remove_moderator_profesion_vtuber_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtuber',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vtubers_photos/'),
        ),
    ]
