# Generated by Django 5.1.3 on 2024-12-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0006_profile_usuario_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
